export const ADD_TASK_REQUEST = "ADD_TASK_REQUEST";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const CHANGE_TASK_REQUEST = "CHANGE_TASK_REQUEST";
export const CHANGE_TASK_SUCCESS = "CHANGE_TASK_SUCCESS";
export const ADD_TASK_FAILURE = "INPROGRESS";
